<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class GejalaSeeder extends Seeder
{
    public function run(): void
    {
        $gejala = [
            ['kode' => 'G001', 'nama' => 'Demam tinggi'],
            ['kode' => 'G002', 'nama' => 'Muntah'],
            ['kode' => 'G003', 'nama' => 'Muntah berulang'],
            ['kode' => 'G004', 'nama' => 'Tidak nafsu makan'],
            ['kode' => 'G005', 'nama' => 'Lemas ekstrem'],
            ['kode' => 'G006', 'nama' => 'Diare cair'],
            ['kode' => 'G007', 'nama' => 'Diare berdarah'],
            ['kode' => 'G008', 'nama' => 'Dehidrasi berat'],
            ['kode' => 'G009', 'nama' => 'Bulu kusam'],
            ['kode' => 'G010', 'nama' => 'Mata cekung'],
            ['kode' => 'G011', 'nama' => 'Bersin'],
            ['kode' => 'G012', 'nama' => 'Batuk'],
            ['kode' => 'G013', 'nama' => 'Pilek / ingusan'],
            ['kode' => 'G014', 'nama' => 'Nafas berbunyi / sesak'],
            ['kode' => 'G015', 'nama' => 'Mata berair / bernanah'],
            ['kode' => 'G016', 'nama' => 'Lesu'],
            ['kode' => 'G017', 'nama' => 'Luka mulut / sariawan'],
            ['kode' => 'G018', 'nama' => 'Air liur berlebihan'],
            ['kode' => 'G019', 'nama' => 'Sakit saat makan'],
            ['kode' => 'G020', 'nama' => 'Perut kembung'],
            ['kode' => 'G021', 'nama' => 'Feses cair'],
            ['kode' => 'G022', 'nama' => 'Alergi makanan'],
            ['kode' => 'G023', 'nama' => 'Diare berulang'],
            ['kode' => 'G024', 'nama' => 'Penurunan berat badan'],
            ['kode' => 'G025', 'nama' => 'Pucat / anemia'],
            ['kode' => 'G026', 'nama' => 'Infeksi berulang'],
            ['kode' => 'G027', 'nama' => 'Bersin dan pilek terus-menerus'],
            ['kode' => 'G028', 'nama' => 'Imun lemah'],
            ['kode' => 'G029', 'nama' => 'Kerontokan bulu melingkar'],
            ['kode' => 'G030', 'nama' => 'Kulit merah bersisik'],
            ['kode' => 'G031', 'nama' => 'Gatal ekstrem'],
            ['kode' => 'G032', 'nama' => 'Kerak tebal pada kulit/telinga'],
            ['kode' => 'G033', 'nama' => 'Kotoran telinga hitam seperti bubuk kopi'],
            ['kode' => 'G034', 'nama' => 'Bau busuk telinga'],
            ['kode' => 'G035', 'nama' => 'Menggelengkan kepala terus'],
            ['kode' => 'G036', 'nama' => 'Nanah keluar dari vagina'],
            ['kode' => 'G037', 'nama' => 'Perut membesar (pembengkakan dalam)'],
            ['kode' => 'G038', 'nama' => 'Puting bengkak dan merah'],
            ['kode' => 'G039', 'nama' => 'Susu bercampur nanah'],
            ['kode' => 'G040', 'nama' => 'Menolak menyusui'],
            ['kode' => 'G041', 'nama' => 'Demam tinggi (laktasi)'],
            ['kode' => 'G042', 'nama' => 'Muntah terus menerus'],
            ['kode' => 'G043', 'nama' => 'Tidak bisa BAB'],
            ['kode' => 'G044', 'nama' => 'Perut keras & kesakitan'],
            ['kode' => 'G045', 'nama' => 'Tidak buang air besar 24–48 jam'],
            ['kode' => 'G046', 'nama' => 'Perubahan perilaku ekstrem / agresif'],
            ['kode' => 'G047', 'nama' => 'Takut air / hydrophobia'],
            ['kode' => 'G048', 'nama' => 'Kejang'],
            ['kode' => 'G049', 'nama' => 'Lumpuh'],
            ['kode' => 'G050', 'nama' => 'Benjolan merah keluar dari anus'],
            ['kode' => 'G051', 'nama' => 'Kesulitan BAB / mengejan terus menerus'],
            ['kode' => 'G052', 'nama' => 'Darah atau lendir dari anus'],
            ['kode' => 'G053', 'nama' => 'Menjilati atau menggigit anus'],
            ['kode' => 'G054', 'nama' => 'Batuk lama / kronis'],
            ['kode' => 'G055', 'nama' => 'Luka mulut berulang'],
            ['kode' => 'G056', 'nama' => 'Kepala miring'],
            ['kode' => 'G057', 'nama' => 'Pipis sedikit-sedikit'],
            ['kode' => 'G058', 'nama' => 'Pipis berdarah'],
            ['kode' => 'G059', 'nama' => 'Sering ke litter box tapi tidak keluar pipis'],
            ['kode' => 'G060', 'nama' => 'Mata bengkak'],
            ['kode' => 'G061', 'nama' => 'Kesakitan saat pipis'],
            ['kode' => 'G062', 'nama' => 'Rambut rontok berlebih'],
            ['kode' => 'G063', 'nama' => 'Telinga bengkak besar'],
            ['kode' => 'G064', 'nama' => 'Muntah busa'],
            ['kode' => 'G065', 'nama' => 'Diare > 3 hari'],
            ['kode' => 'G066', 'nama' => 'Menggigil / sangat lemah'],
            ['kode' => 'G067', 'nama' => 'Nafas melalui mulut'],
            ['kode' => 'G068', 'nama' => 'Kulit sangat gatal & iritasi'],
            ['kode' => 'G069', 'nama' => 'Menelan benda asing'],
            ['kode' => 'G070', 'nama' => 'Sakit waktu buang air'],
            ['kode' => 'G071', 'nama' => 'Tidak bisa buang air sama sekali'],
            ['kode' => 'G072', 'nama' => 'Sering menggigit / agresif berlebihan'],
            ['kode' => 'G073', 'nama' => 'Diare karena makanan basi'],
            ['kode' => 'G074', 'nama' => 'Anak kucing tidak divaksin'],
            ['kode' => 'G075', 'nama' => 'Pernapasan berat'],
            ['kode' => 'G076', 'nama' => 'Mata menguning'],
            ['kode' => 'G077', 'nama' => 'Hidung tersumbat'],
            ['kode' => 'G078', 'nama' => 'Ruangan lembab / stres berat'],
            ['kode' => 'G079', 'nama' => 'Kulit luka bernanah'],
            ['kode' => 'G080', 'nama' => 'Obesitas'],
            ['kode' => 'G081', 'nama' => 'Kurang minum'],
            ['kode' => 'G082', 'nama' => 'Kesakitan ekstrem'],
            ['kode' => 'G083', 'nama' => 'Lesu tidak mau beraktivitas']
        ];

        DB::table('gejala')->insert($gejala);
    }
}
